### ISSUE TITLE
Department automatically switches back to some fixed value

### ISSUE THREAD

**Issue by octomike** [vIiRuS/Lagerregal#142]
One of our users ( :smile_cat: ) is supposed to be a member of department D1 but gets constantly and without interaction switched back to some other department D2.

**Comment by vIiRuS** [comment]
This is most likely caused by the ldapimport command. This sets the main department for a user to a value defined in the ldap/active directory.

**Comment by octomike** [comment]
Yes it is.
Apparently user attributes get synced everytime [ldapimport](https://github.com/vIiRuS/Lagerregal/blob/master/devices/management/commands/ldapimport.py#L98) runs.

What's the reason for this? 

I could think of setting a sync blacklist:
```
AUTH_LDAP_USER_ATTR_NOSYNC = ["LDAP_attr2"]
AUTH_LDAP_USER_ATTR_MAP = {
    "django_field": "LDAP_attr",
    "django_field2": "LDAP_attr2"
}
```

And then test for 
```
if old_value != new_value and attr not in settings.AUTH_LDAP_USER_ATTR_NOSYNC:
    saveuser = True
```
in the same line.

**Comment by vIiRuS** [comment]
This is done in case those attributes change.

This option is added in 5bd4cea82dfe0c49982d570f2f249f158efae64b
